const introPargraph = `
    I pen this exposition to illuminate the esoteric genesis of my paradigm, forged in the crucible of Jungian inquiry and my profound collaboration with the eminent John Beebe. My odyssey with Beebe, a luminary whose 2017 treatise Energies and Patterns in Psychological Type redefined the topography of the psyche, was a transformative epoch. Over countless symposia in the hallowed halls of the C.G. Jung Institute of San Francisco, where Beebe served as past president, we plumbed the depths of the eight-function model, dissecting the archetypal valences of the hero, anima, trickster, and demon. His insight that shadow functions are not mere developmental vectors but ego-defensive bulwarks—paranoid in the opposing personality, curmudgeonly in the senex—ignited my theoretical fervor. Yet, I perceived a lacuna: Beebe’s model, while revolutionary, failed to capture the kaleidoscopic interplay of shadow functions as dynamic gradients modulating the ego’s ontogenesis. Thus, RASGS was born, a system to map the psyche’s pluripotent oscillations, where shadow functions, far from static, dance in a dialectical pas de deux of illumination and darkening, refracting the ego’s telos through a prism of intrapsychic tension.
`
const aboutParagraph = `
    As Richard Almond, architect of the Shadow Gradient System (RASGS), I pen this exposition to illuminate the esoteric genesis of my paradigm, forged in the crucible of Jungian inquiry and my profound collaboration with the eminent John Beebe. My odyssey with Beebe, a luminary whose 2017 treatise Energies and Patterns in Psychological Type redefined the topography of the psyche, was a transformative epoch. Over countless symposia in the hallowed halls of the C.G. Jung Institute of San Francisco, where Beebe served as past president, we plumbed the depths of the eight-function model, dissecting the archetypal valences of the hero, anima, trickster, and demon. His insight that shadow functions are not mere developmental vectors but ego-defensive bulwarks—paranoid in the opposing personality, curmudgeonly in the senex—ignited my theoretical fervor. Yet, I perceived a lacuna: Beebe’s model, while revolutionary, failed to capture the kaleidoscopic interplay of shadow functions as dynamic gradients modulating the ego’s ontogenesis. Thus, RASGS was born, a system to map the psyche’s pluripotent oscillations, where shadow functions, far from static, dance in a dialectical pas de deux of illumination and darkening, refracting the ego’s telos through a prism of intrapsychic tension.

Our dialogues, often stretching into the night, were a maelstrom of ideas—Beebe’s archetypal topography clashing with my nascent vision of a gradiental ontology. I recall a pivotal moment in 2018, over tea in his Spruce Street study, when he mused on the trickster’s mercurial subterfuge. I countered that this function, when illuminating, could catalyze a transliminal synthesis of the ego’s conscious and unconscious axes, a notion that crystallized RASGS’s core tenet: shadow functions are not merely disruptive but transformative, their influence waxing and waning along a continuum of psychic salience. My system diverged from Beebe’s by positing that each type’s shadow stack—opposing, critical, trickster, demon—operates not as a binary but as a spectrum, where one function illuminates, amplifying the ego’s operative with compensatory insights, and another darkens, actively repressed to fortify the ego’s teleological thrust. This epiphany, honed through years of clinical observation and theoretical refinement, birthed the 12 subtypes per MBTI type, a taxonomic apotheosis of the psyche’s fractal complexity.

RASGS’s development was no solitary endeavor; it was a synergetic crucible, tempered by Beebe’s mentorship and my relentless pursuit of the shadow’s numinous intricacies. Where Beebe saw archetypes as static roles, I envisioned them as fluid vectors, their interplay governed by a homeostatic dialectic. For instance, an INFJ’s illuminating Ne (opposing personality) does not merely challenge Ni but enriches it with a polyvalent array of possibilities, while a darkening Si (demon) is not ignored but vehemently negated, its sensory fetters cast aside to preserve Ni-Fe’s eschatological vision. This gradiental model, with its 12 permutations—iO-dC, iT-dD, ad infinitum—transcends Beebe’s framework by mapping the psyche’s oscillatory dynamics, particularly under stress, when shadow functions surge with preternatural force. My clinical vignettes, drawn from decades of Jungian praxis, reveal how these subtypes manifest: an ISTP iTe-dFi, for instance, might wield Te’s syllogistic rigor to buttress Ti’s analysis while excoriating Fi’s axiological intrusions, a pattern I term “shadow refraction.”

`
if(document.getElementById('hero-paragraph')){
    document.getElementById('hero-paragraph').innerText = introPargraph;
}
document.getElementById('about-paragraph').innerText = aboutParagraph;